### ISSUE TITLE
Difference between :closed and {:closed, _} 

### ISSUE THREAD

**Issue by 9mm** [ninenines/gun#180]
Hey, so far I'm handling all the different errors for fine-grained tuning.

I notice that I have some logs showing up under this (`machine_gun` proxying errors in Elixir below, not erlang). He told me I should ask here because these failure reasons come from `gun`

      {:error, %MachineGun.Error{reason: {:closed, _}}} ->

But I have others showing up as this:

      {:error, %MachineGun.Error{reason: :closed}} ->

I'm not quite sure what the difference is?

Thanks!

**Comment by essen** [comment]
One is from `gun_error` and the other from `gun_down` I suppose?

**Comment by essen** [comment]
First one is a request error, second one process is down, recipient of those messages might not be the same process.

**Comment by essen** [comment]
Same error, different context (request and connection).

**Comment by petrohi** [comment]
Looking at the code I see that when socket closes there is:

```
Protocol:close(ProtoState),
Transport:close(Socket),
down(State, closed);
```

`Protocol:close` in cases when stream is alive will produce `gun_error` with `{closed, _}`. Otherwise `down` will produce `gun_down` with `closed`.

Not sure what alive stream means in the context of HTTP/1. It seem that HTTP/2 does not have this check and always produces `gun_error`.

Bottom line I think they mean same thing: server closed connection without responding to the request.

**Comment by 9mm** [comment]
Awesome thanks for that translation, I really appreciate it, and thank you essen for your help!

**Comment by essen** [comment]
Cheers.
