### ISSUE TITLE
Compile-time warnings under rebar3

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [ninenines/gun#259]
I get issued one warning of type:

```erlang
===> WARNING: It is recommended to use {branch, Name}, {tag, Tag} or {ref, Ref},
otherwise updating the dep may not work as expected.
```

for `cowlib`.

Would you accept a pull request where `"2.10.1"` is updated to `{git, "2.10.1"}`?

Not doing that also seems to implicate (upon `rebar3 upgrade`) `cowlib` get constantly re-fetched/re-compiled, something which could be avoided.

**Comment by essen** [comment]
No because the file is automatically generated. I'm only welcome to a solution that modifies the generator code in Erlang.mk.

**Comment by paulo-ferraz-oliveira** [comment]
Sure. Any pointers on where I could start looking? I've never used `Erlang.mk` in the past, but am more than happy to.

**Comment by essen** [comment]
https://github.com/ninenines/erlang.mk/blob/master/core/compat.mk

The problem is knowing whether you're on a branch, tag, or other. Erlang.mk does not have this information.

**Comment by paulo-ferraz-oliveira** [comment]
Ah, I see, so you mean it's not worth tackling? Or simply that it would imply changes you'd prefer not be done in `erlang.mk`?

**Comment by essen** [comment]
Neither. Just saying you would have to figure out whether it's a branch, tag or ref while generating the rebar.config file, because this information is not available to Erlang.mk through configuration. Updating a branch for example is just a matter of deleting the relevant directory, so it's not useful information. Not sure if `git` provides an interface to know what type of object is referred to, but if it does I'm not against modifying the rebar.config generator to include this information.
